import { QuizQuestion, StudentNote, LearnerPersona } from '../types';

/**
 * Fetch AI-generated mastery quiz questions strictly from Gemini AI.
 * No static or premade questions are stored in code.
 */
export async function fetchAIQuizQuestions(
  note: StudentNote,
  persona?: LearnerPersona,
  count: number = 5
): Promise<QuizQuestion[]> {
  // 1. If note already has questions generated by AI from earlier, return them
  if (note.quiz?.questions && Array.isArray(note.quiz.questions) && note.quiz.questions.length >= 3) {
    return note.quiz.questions;
  }

  // 2. Call the server's Gemini AI endpoint to synthesize questions from note content
  const res = await fetch('/api/ai/quiz/generate-mastery-quiz', {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify({
      noteContent: note.personalisedNotes || note.content || '',
      title: note.title,
      count,
      learnerProfile: persona
    })
  });

  if (!res.ok) {
    throw new Error(`Gemini AI service responded with status ${res.status}`);
  }

  const data = await res.json();
  if (!Array.isArray(data.questions) || data.questions.length === 0) {
    throw new Error('Gemini AI returned an empty question set.');
  }

  return data.questions;
}

/**
 * Retrieves pre-saved AI questions from the note if already generated.
 * Does not return any hardcoded or premade questions.
 */
export function getOrGenerateQuizQuestions(
  note: StudentNote,
  _persona?: LearnerPersona
): QuizQuestion[] {
  if (note.quiz?.questions && Array.isArray(note.quiz.questions) && note.quiz.questions.length >= 3) {
    return note.quiz.questions.map((q, idx) => ({
      id: q.id || `q-saved-${idx}`,
      question: q.question,
      options: q.options,
      correctIndex: q.correctIndex,
      explanation: q.explanation || 'Verified from curriculum notes.',
      topic: q.topic || note.title.slice(0, 30),
      difficulty: (q.difficulty || 'moderate') as 'easy' | 'moderate' | 'hard'
    }));
  }

  // Return empty array if not yet generated by AI so the UI triggers the AI generator
  return [];
}
